"""Add member biography section

Revision ID: 0d0f30daff78
Revises: f7fb13223fab
Create Date: 2017-06-16 19:54:18.987645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0f30daff78'
down_revision = 'f7fb13223fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('biography', sa.String(length=10000), nullable=True, server_default="This biography field gets rendered as _Markdown_\n\nYou can\n* use bullets\n* [format links](https://example.com)\n* [and more](http://commonmark.org)!"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'biography')
    # ### end Alembic commands ###
