"""Add email routing tables

Revision ID: c0cf4c2546e7
Revises: 0d0f30daff78
Create Date: 2017-06-26 20:40:04.186423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cf4c2546e7'
down_revision = '0d0f30daff78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=254), nullable=True),
    sa.Column('email_address', sa.String(length=254), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('forwarding_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forward_to', sa.String(length=254), nullable=True),
    sa.Column('incoming_email_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incoming_email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forwarding_addresses')
    op.drop_table('emails')
    # ### end Alembic commands ###
