"""Fix attendee models

Revision ID: f7fb13223fab
Revises: 17cca4a9d477
Create Date: 2017-06-15 20:55:15.116883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fb13223fab'
down_revision = '17cca4a9d477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendees', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attendees', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendees', type_='foreignkey')
    op.drop_column('attendees', 'member_id')
    # ### end Alembic commands ###
